name: another_transformer_page_view
description: Yet another pageTransformer for flutter with null-safety support
version: 1.0.2
repository: https://github.com/juliansteenbakker/another_transformer_page_view

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.4